spring:
  application:
    name: "mock-stock-server"

project:
  version: 0.0.1

jwt:
  secret:
    access: ${JWT_ACCESS_SECRET}
    refresh: ${JWT_REFRESH_SECRET}

logging:
  level:
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:13306/stock?serverTimezone=UTC&characterEncoding=UTF-8
    username: min9805
    password: backend
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    mongodb:
        host: localhost
        port: 27018
        database: stock
        username: admin
        password: admin_password
        authentication-database: admin
  redis:
    host: localhost
    port: 6379